if (!window.PDoc) window.PDoc = {};
PDoc.elements = {
  'wysihat section': { 'name': 'wysihat section', 'type': 'section', 'path': 'wysihat.html#wysihat_section-section' },
'WysiHat': { 'name': 'WysiHat', 'type': 'namespace', 'path': 'wysihat/wysihat.html' },
'WysiHat.Editor': { 'name': 'WysiHat.Editor', 'type': 'namespace', 'path': 'wysihat/wysihat/editor.html' },
'WysiHat.Editor.attach': { 'name': 'WysiHat.Editor.attach', 'type': 'class method', 'path': 'wysihat/wysihat/editor.html#attach-class_method' },
'WysiHat.Editor.include': { 'name': 'WysiHat.Editor.include', 'type': 'class method', 'path': 'wysihat/wysihat/editor.html#include-class_method' },
'WysiHat.Commands': { 'name': 'WysiHat.Commands', 'type': 'mixin', 'path': 'wysihat/wysihat/commands.html' },
'WysiHat.Commands#boldSelection': { 'name': 'WysiHat.Commands#boldSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#boldselection-instance_method' },
'WysiHat.Commands#boldSelected': { 'name': 'WysiHat.Commands#boldSelected', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#boldselected-instance_method' },
'WysiHat.Commands#underlineSelection': { 'name': 'WysiHat.Commands#underlineSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#underlineselection-instance_method' },
'WysiHat.Commands#underlineSelected': { 'name': 'WysiHat.Commands#underlineSelected', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#underlineselected-instance_method' },
'WysiHat.Commands#italicSelection': { 'name': 'WysiHat.Commands#italicSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#italicselection-instance_method' },
'WysiHat.Commands#italicSelected': { 'name': 'WysiHat.Commands#italicSelected', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#italicselected-instance_method' },
'WysiHat.Commands#italicSelection': { 'name': 'WysiHat.Commands#italicSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#italicselection-instance_method' },
'WysiHat.Commands#blockquoteSelection': { 'name': 'WysiHat.Commands#blockquoteSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#blockquoteselection-instance_method' },
'WysiHat.Commands#colorSelection': { 'name': 'WysiHat.Commands#colorSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#colorselection-instance_method' },
'WysiHat.Commands#linkSelection': { 'name': 'WysiHat.Commands#linkSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#linkselection-instance_method' },
'WysiHat.Commands#unlinkSelection': { 'name': 'WysiHat.Commands#unlinkSelection', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#unlinkselection-instance_method' },
'WysiHat.Commands#linkSelected': { 'name': 'WysiHat.Commands#linkSelected', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#linkselected-instance_method' },
'WysiHat.Commands#insertOrderedList': { 'name': 'WysiHat.Commands#insertOrderedList', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#insertorderedlist-instance_method' },
'WysiHat.Commands#insertUnorderedList': { 'name': 'WysiHat.Commands#insertUnorderedList', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#insertunorderedlist-instance_method' },
'WysiHat.Commands#insertImage': { 'name': 'WysiHat.Commands#insertImage', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#insertimage-instance_method' },
'WysiHat.Commands#insertHTML': { 'name': 'WysiHat.Commands#insertHTML', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#inserthtml-instance_method' },
'WysiHat.Commands#execCommand': { 'name': 'WysiHat.Commands#execCommand', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#execcommand-instance_method' },
'WysiHat.Commands#queryCommandState': { 'name': 'WysiHat.Commands#queryCommandState', 'type': 'instance method', 'path': 'wysihat/wysihat/commands.html#querycommandstate-instance_method' },
'WysiHat.Events': { 'name': 'WysiHat.Events', 'type': 'mixin', 'path': 'wysihat/wysihat/events.html' },
'WysiHat.Persistence': { 'name': 'WysiHat.Persistence', 'type': 'mixin', 'path': 'wysihat/wysihat/persistence.html' },
'WysiHat.Persistence#outputFilter': { 'name': 'WysiHat.Persistence#outputFilter', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#outputfilter-instance_method' },
'WysiHat.Persistence#inputFilter': { 'name': 'WysiHat.Persistence#inputFilter', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#inputfilter-instance_method' },
'WysiHat.Persistence#content': { 'name': 'WysiHat.Persistence#content', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#content-instance_method' },
'WysiHat.Persistence#setContent': { 'name': 'WysiHat.Persistence#setContent', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#setcontent-instance_method' },
'WysiHat.Persistence#save': { 'name': 'WysiHat.Persistence#save', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#save-instance_method' },
'WysiHat.Persistence#load': { 'name': 'WysiHat.Persistence#load', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#load-instance_method' },
'WysiHat.Persistence#reload': { 'name': 'WysiHat.Persistence#reload', 'type': 'instance method', 'path': 'wysihat/wysihat/persistence.html#reload-instance_method' },
'WysiHat.Window': { 'name': 'WysiHat.Window', 'type': 'mixin', 'path': 'wysihat/wysihat/window.html' },
'WysiHat.Window#getDocument': { 'name': 'WysiHat.Window#getDocument', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#getdocument-instance_method' },
'WysiHat.Window#getWindow': { 'name': 'WysiHat.Window#getWindow', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#getwindow-instance_method' },
'WysiHat.Window#focus': { 'name': 'WysiHat.Window#focus', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#focus-instance_method' },
'WysiHat.Window#blur': { 'name': 'WysiHat.Window#blur', 'type': 'instance method', 'path': 'wysihat/wysihat/window.html#blur-instance_method' },
'WysiHat.iFrame': { 'name': 'WysiHat.iFrame', 'type': 'namespace', 'path': 'wysihat/wysihat/iframe.html' },
'WysiHat.iFrame.Methods': { 'name': 'WysiHat.iFrame.Methods', 'type': 'mixin', 'path': 'wysihat/wysihat/iframe/methods.html' },
'WysiHat.iFrame#whenReady': { 'name': 'WysiHat.iFrame#whenReady', 'type': 'instance method', 'path': 'wysihat/wysihat/iframe.html#whenready-instance_method' },
'WysiHat.iFrame.Methods#setStyle': { 'name': 'WysiHat.iFrame.Methods#setStyle', 'type': 'instance method', 'path': 'wysihat/wysihat/iframe/methods.html#setstyle-instance_method' },
'WysiHat.Editable': { 'name': 'WysiHat.Editable', 'type': 'namespace', 'path': 'wysihat/wysihat/editable.html' },
'WysiHat.Editable.Methods': { 'name': 'WysiHat.Editable.Methods', 'type': 'mixin', 'path': 'wysihat/wysihat/editable/methods.html' },
'lang section': { 'name': 'lang section', 'type': 'section', 'path': 'lang.html#lang_section-section' },
'String': { 'name': 'String', 'type': 'class', 'path': 'lang/string.html' },
'String#formatHTMLOutput': { 'name': 'String#formatHTMLOutput', 'type': 'instance method', 'path': 'lang/string.html#formathtmloutput-instance_method' },
'String#formatHTMLInput': { 'name': 'String#formatHTMLInput', 'type': 'instance method', 'path': 'lang/string.html#formathtmlinput-instance_method' },
'String#tidyXHTML': { 'name': 'String#tidyXHTML', 'type': 'instance method', 'path': 'lang/string.html#tidyxhtml-instance_method' },
'String': { 'name': 'String', 'type': 'class', 'path': 'lang/string.html' },
'String#sanitize': { 'name': 'String#sanitize', 'type': 'instance method', 'path': 'lang/string.html#sanitize-instance_method' },
'dom section': { 'name': 'dom section', 'type': 'section', 'path': 'dom.html#dom_section-section' },
'Range': { 'name': 'Range', 'type': 'class', 'path': 'dom/range.html' },
'Range#cloneContents': { 'name': 'Range#cloneContents', 'type': 'instance method', 'path': 'dom/range.html#clonecontents-instance_method' },
'Range#cloneRange': { 'name': 'Range#cloneRange', 'type': 'instance method', 'path': 'dom/range.html#clonerange-instance_method' },
'Range#collapse': { 'name': 'Range#collapse', 'type': 'instance method', 'path': 'dom/range.html#collapse-instance_method' },
'Range#compareBoundaryPoints': { 'name': 'Range#compareBoundaryPoints', 'type': 'instance method', 'path': 'dom/range.html#compareboundarypoints-instance_method' },
'Range#deleteContents': { 'name': 'Range#deleteContents', 'type': 'instance method', 'path': 'dom/range.html#deletecontents-instance_method' },
'Range#detach': { 'name': 'Range#detach', 'type': 'instance method', 'path': 'dom/range.html#detach-instance_method' },
'Range#extractContents': { 'name': 'Range#extractContents', 'type': 'instance method', 'path': 'dom/range.html#extractcontents-instance_method' },
'Range#insertNode': { 'name': 'Range#insertNode', 'type': 'instance method', 'path': 'dom/range.html#insertnode-instance_method' },
'Range#selectNode': { 'name': 'Range#selectNode', 'type': 'instance method', 'path': 'dom/range.html#selectnode-instance_method' },
'Range#selectNodeContents': { 'name': 'Range#selectNodeContents', 'type': 'instance method', 'path': 'dom/range.html#selectnodecontents-instance_method' },
'Range#setStart': { 'name': 'Range#setStart', 'type': 'instance method', 'path': 'dom/range.html#setstart-instance_method' },
'Range#setStartAfter': { 'name': 'Range#setStartAfter', 'type': 'instance method', 'path': 'dom/range.html#setstartafter-instance_method' },
'Range#setStartBefore': { 'name': 'Range#setStartBefore', 'type': 'instance method', 'path': 'dom/range.html#setstartbefore-instance_method' },
'Range#setEnd': { 'name': 'Range#setEnd', 'type': 'instance method', 'path': 'dom/range.html#setend-instance_method' },
'Range#setEndAfter': { 'name': 'Range#setEndAfter', 'type': 'instance method', 'path': 'dom/range.html#setendafter-instance_method' },
'Range#setEndBefore': { 'name': 'Range#setEndBefore', 'type': 'instance method', 'path': 'dom/range.html#setendbefore-instance_method' },
'Range#surroundContents': { 'name': 'Range#surroundContents', 'type': 'instance method', 'path': 'dom/range.html#surroundcontents-instance_method' },
'WysiHat.Selection': { 'name': 'WysiHat.Selection', 'type': 'class', 'path': 'dom/wysihat/selection.html' },
'new WysiHat.Selection': { 'name': 'new WysiHat.Selection', 'type': 'constructor', 'path': 'dom/wysihat/selection.html#new-constructor' },
'WysiHat.Selection#getSelection': { 'name': 'WysiHat.Selection#getSelection', 'type': 'instance method', 'path': 'dom/wysihat/selection.html#getselection-instance_method' },
'WysiHat.Selection#getRange': { 'name': 'WysiHat.Selection#getRange', 'type': 'instance method', 'path': 'dom/wysihat/selection.html#getrange-instance_method' },
'WysiHat.Selection#selectNode': { 'name': 'WysiHat.Selection#selectNode', 'type': 'instance method', 'path': 'dom/wysihat/selection.html#selectnode-instance_method' },
'WysiHat.Selection#getNode': { 'name': 'WysiHat.Selection#getNode', 'type': 'instance method', 'path': 'dom/wysihat/selection.html#getnode-instance_method' },
'WysiHat.Toolbar': { 'name': 'WysiHat.Toolbar', 'type': 'class', 'path': 'wysihat/wysihat/toolbar.html' },
'new WysiHat.Toolbar': { 'name': 'new WysiHat.Toolbar', 'type': 'constructor', 'path': 'wysihat/wysihat/toolbar.html#new-constructor' },
'WysiHat.Toolbar#createToolbarElement': { 'name': 'WysiHat.Toolbar#createToolbarElement', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#createtoolbarelement-instance_method' },
'WysiHat.Toolbar#addButtonSet': { 'name': 'WysiHat.Toolbar#addButtonSet', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#addbuttonset-instance_method' },
'WysiHat.Toolbar#addButton': { 'name': 'WysiHat.Toolbar#addButton', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#addbutton-instance_method' },
'WysiHat.Toolbar#createButtonElement': { 'name': 'WysiHat.Toolbar#createButtonElement', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#createbuttonelement-instance_method' },
'WysiHat.Toolbar#buttonHandler': { 'name': 'WysiHat.Toolbar#buttonHandler', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#buttonhandler-instance_method' },
'WysiHat.Toolbar#observeButtonClick': { 'name': 'WysiHat.Toolbar#observeButtonClick', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#observebuttonclick-instance_method' },
'WysiHat.Toolbar#buttonStateHandler': { 'name': 'WysiHat.Toolbar#buttonStateHandler', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#buttonstatehandler-instance_method' },
'WysiHat.Toolbar#observeStateChanges': { 'name': 'WysiHat.Toolbar#observeStateChanges', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#observestatechanges-instance_method' },
'WysiHat.Toolbar#updateButtonState': { 'name': 'WysiHat.Toolbar#updateButtonState', 'type': 'instance method', 'path': 'wysihat/wysihat/toolbar.html#updatebuttonstate-instance_method' },
'WysiHat.Toolbar.ButtonSets': { 'name': 'WysiHat.Toolbar.ButtonSets', 'type': 'namespace', 'path': 'wysihat/wysihat/toolbar/buttonsets.html' },
'WysiHat.Toolbar.ButtonSets.Basic': { 'name': 'WysiHat.Toolbar.ButtonSets.Basic', 'type': 'namespace', 'path': 'wysihat/wysihat/toolbar/buttonsets/basic.html' }
};